fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: end-of-file-fixer

- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.17
  hooks:
    - id: shellcheck
      args: ["./hooks/*.sh"]
