- id: ansible-requirements-versions
  name: Ansible Requirements Versions
  description: Uses lastversion to check versions of Ansible roles from Git repos to see if the one defined is the latest.
  language: python
  entry: hooks/check-ansible-requirements.py
  files: requirements.yml
  additional_dependencies: [lastversion]
